

#' Orders a expression stability data frame by stability value
#'
#' @param df An expression stability matrix, tibble or data frame, should have expression stabilities in second column
#'
#' @return An ordered data frame
#'
#' @export
#' @examples
#' ct_vals <- matrix(rnorm(5*20), ncol = 5, nrow = 20)
#' dimnames(ct_vals)[[2]] <-  c("gene1", "gene2", "gene3", "gene4", "gene5")
#'
#' dct <- rf_deltaCt(ct_vals)
#'
#' dct <- rforderbystability(dct)
#' dct
#'
rforderbystability <- function(df){
  df <- df[order(df[,2]),]
  row.names(df) <- NULL
  return(df)
}






#' Adds a ranking colum to at stability table. If two targets have equal stabilities they are given the same rank.
#'
#' @param stabilitytable A stability table, normally generated by an rf algorithm
#' @param stabilitycol A number indicating the column holding the stability values
#'
#' @return A stability table with ranking column
#' @export
#'
# #' @examples

rfaddstabilityrank <- function(stabilitytable, stabilitycol) {


  stabilitytable <- rforderbystability(stabilitytable)
  stabilitytable$'Stability Rank' <- order(stabilitytable[ ,stabilitycol])


  for (i in 2:nrow(stabilitytable)) {
    if(stabilitytable[i, stabilitycol] == stabilitytable[(i-1), stabilitycol]){
      stabilitytable$`Stability Rank`[i] = stabilitytable$`Stability Rank`[i-1]
    }
  }

  return(stabilitytable)
}




#
# rfaddstabilityrank <- function(stabilitytable, stabilitycol) {
#
#
#   stabilitytable <- rforderbystability(stabilitytable)
#   stabilitytable$'Stability Rank' <- order(stabilitytable$Stability)
#
#
#   for (i in 2:nrow(stabilitytable)) {
#     if(stabilitytable$Stability[i] == stabilitytable$Stability[i-1]){
#       stabilitytable$`Stability Rank`[i] = stabilitytable$`Stability Rank`[i-1]
#     }
#   }
#
#   return(stabilitytable)
# }
